apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test-auto"
  description: example.com
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/adr-location: docs/adrs
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
  system: example-center
